### ISSUE TITLE
建议使用 github pages 做博客

### ISSUE THREAD

**Issue by sinkcup** [ZhangChaoWN/notes#1]
这个项目没有发布成 博客网站啊？建议使用 github pages

**Comment by ZhangChaoWN** [comment]
感谢提建议，现在发布成 github pages 网站了，不得不感慨下用 github pages 做网站的体验，git push 完就不用管了，网站自动上线，整个流程丝般顺滑

**Comment by sinkcup** [comment]
@ZhangChaoWN 你的代码提交错了分支，fork 不是这样用的。在网页上直接修改别人的开源项目代码，会自动帮你创建正确的流程：fork -> patch-1 分支 -> 跨项目 PR -> 管理员合并到主干 -> 你 sync fork

https://help.github.com/articles/syncing-a-fork/

![image](https://user-images.githubusercontent.com/4971414/79677186-2127a780-8221-11ea-83e2-44ee983d3ea7.png)
